# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\david\Documents\PYTHON\interfaz_motor\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lab2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lab2.setFont(font)
        self.lab2.setStyleSheet("color: green;")
        self.lab2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab2.setObjectName("lab2")
        self.gridLayout.addWidget(self.lab2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(400, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\david\\Documents\\PYTHON\\interfaz_motor\\auto.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 3, 3, 2)
        self.lab1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lab1.setFont(font)
        self.lab1.setStyleSheet("color: green;")
        self.lab1.setAlignment(QtCore.Qt.AlignCenter)
        self.lab1.setObjectName("lab1")
        self.gridLayout.addWidget(self.lab1, 1, 0, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.frame)
        self.btn1.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton{\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:0px;\n"
"background-color: rgb(130, 224, 170);\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius:0px;\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"")
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 3, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.frame)
        self.btn2.setMinimumSize(QtCore.QSize(200, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton{\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:0px;\n"
"background-color: rgb(130, 224, 170);\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius:0px;\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"")
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 3, 1, 1, 1)
        self.lab3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lab3.setFont(font)
        self.lab3.setStyleSheet("color: green;")
        self.lab3.setAlignment(QtCore.Qt.AlignCenter)
        self.lab3.setObjectName("lab3")
        self.gridLayout.addWidget(self.lab3, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(41, 128, 185);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 5)
        self.btn3 = QtWidgets.QPushButton(self.frame)
        self.btn3.setMinimumSize(QtCore.QSize(200, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("QPushButton{\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:0px;\n"
"background-color: rgb(130, 224, 170);\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius:0px;\n"
"background-color: rgb(88, 214, 141 );\n"
"border-radius:3px;\n"
"color:white\n"
"}\n"
"")
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\david\\Documents\\PYTHON\\interfaz_motor\\logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab2.setText(_translate("MainWindow", "ON"))
        self.lab1.setText(_translate("MainWindow", "ON"))
        self.btn1.setText(_translate("MainWindow", "SISTEMA DE CARGA"))
        self.btn2.setText(_translate("MainWindow", "SISTEMA DE ALIMENTACION"))
        self.lab3.setText(_translate("MainWindow", "ON"))
        self.label_5.setText(_translate("MainWindow", "Sistema Generador de Fallos"))
        self.btn3.setText(_translate("MainWindow", "SISTEMA DE ENCENDIDO"))
